// Generated by scripts/sync_feature_schema.py; do not edit.
// Column order is part of the persisted model contract.
pub(crate) const FULL_FEATURE_COUNT: usize = 33;

pub(crate) const FIRST_NAMES_EQUAL: usize = 0;
pub(crate) const MIDDLE_INITIALS_OVERLAP: usize = 1;
pub(crate) const MIDDLE_NAMES_EQUAL: usize = 2;
pub(crate) const MIDDLE_ONE_MISSING: usize = 3;
pub(crate) const SINGLE_CHAR_FIRST: usize = 4;
pub(crate) const SINGLE_CHAR_MIDDLE: usize = 5;
pub(crate) const AFFILIATION_OVERLAP: usize = 6;
pub(crate) const EMAIL_PREFIX_EQUAL: usize = 7;
pub(crate) const EMAIL_SUFFIX_EQUAL: usize = 8;
pub(crate) const COAUTHOR_OVERLAP: usize = 9;
pub(crate) const COAUTHOR_SIMILARITY: usize = 10;
pub(crate) const COAUTHOR_MATCH: usize = 11;
pub(crate) const VENUE_OVERLAP: usize = 12;
pub(crate) const YEAR_DIFF: usize = 13;
pub(crate) const TITLE_OVERLAP_WORDS: usize = 14;
pub(crate) const TITLE_OVERLAP_CHARS: usize = 15;
pub(crate) const POSITION_DIFF: usize = 16;
pub(crate) const ABSTRACT_COUNT: usize = 17;
pub(crate) const ENGLISH_COUNT: usize = 18;
pub(crate) const SAME_LANGUAGE: usize = 19;
pub(crate) const LANGUAGE_RELIABILITY_MIN: usize = 20;
pub(crate) const FIRST_NAME_COUNT_MIN: usize = 21;
pub(crate) const LAST_FIRST_NAME_COUNT_MIN: usize = 22;
pub(crate) const LAST_NAME_COUNT_MIN: usize = 23;
pub(crate) const LAST_FIRST_INITIAL_COUNT_MIN: usize = 24;
pub(crate) const FIRST_NAME_COUNT_MAX: usize = 25;
pub(crate) const LAST_FIRST_NAME_COUNT_MAX: usize = 26;
pub(crate) const SPECTER_COSINE_SIM: usize = 27;
pub(crate) const JOURNAL_OVERLAP: usize = 28;
pub(crate) const LEVENSHTEIN: usize = 29;
pub(crate) const PREFIX: usize = 30;
pub(crate) const LCS: usize = 31;
pub(crate) const JARO: usize = 32;
