[package]
name = "s2and_rust"
version = "1.0.0"
edition = "2021"

[lib]
name = "_s2and_rust"
crate-type = ["cdylib"]

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "0.24.2" }
numpy = "0.24"
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
cld2 = "1.0.2"
serde_json = "1.0"
sha2 = "0.10"
arrow = { version = "54", default-features = false, features = ["ipc"] }
unidecode = "0.3.0"
memmap2 = "0.9"
unicode-properties = "0.1"

[patch.crates-io]
cld2 = { path = "vendor/cld2" }
