"""Generate Rust column constants from the authoritative Python feature schema."""

import argparse
import runpy
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "s2and" / "feature_schema.py"
RUST_PATH = ROOT / "s2and_rust" / "src" / "feature_schema.rs"


def render_rust_schema() -> str:
    """Render named column constants without importing the S2AND runtime."""
    schema = runpy.run_path(str(SCHEMA_PATH))["FEATURE_SCHEMA"]
    lines = [
        "// Generated by scripts/sync_feature_schema.py; do not edit.",
        "// Column order is part of the persisted model contract.",
        f"pub(crate) const FULL_FEATURE_COUNT: usize = {len(schema)};",
        "",
    ]
    lines.extend(f"pub(crate) const {feature.name.upper()}: usize = {index};" for index, feature in enumerate(schema))
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> None:
    """Write generated constants or fail when the checked-in copy is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the generated Rust constants without writing")
    args = parser.parse_args(argv)
    expected = render_rust_schema()
    if args.check:
        if not RUST_PATH.is_file() or RUST_PATH.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "Rust feature schema is stale; run uv run --no-project python scripts/sync_feature_schema.py"
            )
        print("Feature schema is synchronized")
    else:
        RUST_PATH.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Wrote {RUST_PATH}")


if __name__ == "__main__":
    main()
