"""Public raw-planner Arrow module.

Implementation is split across compact contracts and Arrow IO helpers.
"""

from __future__ import annotations

from s2and.incremental_linking.feature_block_arrow import (
    ARROW_BATCH_LOOKUP_INDEX_SCHEMA_VERSION,
    ARROW_PHYSICAL_LAYOUT_SCHEMA_VERSION,
    NAME_COUNTS_INDEX_SCHEMA_VERSION,
    RAW_PLANNER_ARROW_BATCH_INDEX_KEYS,
    RAW_PLANNER_ARROW_KEY_COLUMNS,
    RAW_PLANNER_ARROW_MAX_RECORD_BATCH_ROWS,
    IncrementalQuerySignatureRequest,
    arrow_ipc_physical_layout,
    cluster_seed_disallows_from_arrow_paths,
    cluster_seed_disallows_path_from_arrow_paths,
    raw_planner_arrow_physical_layout,
    read_altered_cluster_signatures_arrow,
    read_arrow_batch_lookup_index_batch_indices,
    read_cluster_seed_disallows_arrow,
    read_cluster_seeds_arrow,
    read_incremental_query_signatures_arrow,
    temporary_arrow_paths_with_cluster_seeds,
    validate_arrow_batch_lookup_index,
    write_altered_cluster_signatures_arrow,
    write_arrow_batch_lookup_index,
    write_arrow_ipc_table,
    write_cluster_seed_disallows_arrow,
    write_cluster_seeds_arrow,
    write_incremental_query_signatures_arrow,
    write_name_counts_index,
    write_raw_arrow_batch_lookup_indexes,
    write_raw_planner_arrow_tables,
)
from s2and.incremental_linking.feature_block_contract import (
    FEATURE_BLOCK_ARROW_MANIFEST_SCHEMA_VERSION,
    FEATURE_BLOCK_SCHEMA_VERSION,
    FeatureBlockSignatureOrder,
    normalize_cluster_seed_disallow_pairs,
)

__all__ = [
    "ARROW_BATCH_LOOKUP_INDEX_SCHEMA_VERSION",
    "ARROW_PHYSICAL_LAYOUT_SCHEMA_VERSION",
    "FEATURE_BLOCK_ARROW_MANIFEST_SCHEMA_VERSION",
    "FEATURE_BLOCK_SCHEMA_VERSION",
    "NAME_COUNTS_INDEX_SCHEMA_VERSION",
    "RAW_PLANNER_ARROW_BATCH_INDEX_KEYS",
    "RAW_PLANNER_ARROW_KEY_COLUMNS",
    "RAW_PLANNER_ARROW_MAX_RECORD_BATCH_ROWS",
    "FeatureBlockSignatureOrder",
    "IncrementalQuerySignatureRequest",
    "arrow_ipc_physical_layout",
    "cluster_seed_disallows_from_arrow_paths",
    "cluster_seed_disallows_path_from_arrow_paths",
    "normalize_cluster_seed_disallow_pairs",
    "raw_planner_arrow_physical_layout",
    "read_altered_cluster_signatures_arrow",
    "read_arrow_batch_lookup_index_batch_indices",
    "read_cluster_seed_disallows_arrow",
    "read_cluster_seeds_arrow",
    "read_incremental_query_signatures_arrow",
    "temporary_arrow_paths_with_cluster_seeds",
    "validate_arrow_batch_lookup_index",
    "write_altered_cluster_signatures_arrow",
    "write_arrow_batch_lookup_index",
    "write_arrow_ipc_table",
    "write_cluster_seed_disallows_arrow",
    "write_cluster_seeds_arrow",
    "write_incremental_query_signatures_arrow",
    "write_name_counts_index",
    "write_raw_planner_arrow_tables",
    "write_raw_arrow_batch_lookup_indexes",
]
