name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        docker build --tag s2and .
        docker run --rm s2and pytest tests/ --verbose
        docker run --rm s2and black s2and --check --line-length 120
        docker run --rm s2and black scripts/*.py --check --line-length 120
        docker run --rm s2and bash scripts/mypy.sh
        docker run --rm s2and pytest tests/ --cov s2and --cov-fail-under=40
